# LOG4J配置
log4j:
  rootCategory: INFO,stdout
  # 控制台输出
  appender:
    stdout: org.apache.log4j.ConsoleAppender
      layout: org.apache.log4j.PatternLayout
        ConversionPattern: %d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n